use crate::Treasures;

impl Treasures {
    pub(crate) const TREASURES: &[&'static str] = &[
        "The only entertainment of Arkady's homeworld",
        "Something you could ask your mother, if she wasn't a fucking lamp",
        "Time turning, tides turbulent",
        "The night critters' allowance",
        "A front porch light and the knowledge of nostos",
        "A volume impossible astronauts find in libraries",
        "Loki's smile",
        "Invention, ricochet and silence",
        "The burning shoulder and spinning belt of Orion",
        "A body whose veins are electricity",
        "Morning in Salwa",
        "What any modern officer has a pretty taste for",
        "Selmers' rhymes",
        "Hephaistos' greeting to Romans ...",
        "A feast, a theft, a plague progressing",
        "Wildfires in Tulsa",
        "Hyperpotamous travel",
        "Origins of the Bee Swarm",
        "Modela aperatifs",
        "White crocus for the many below",
        "A Belligerent boat",
        "Natsworthy's smile",
        "The best pre-Pedro Pascal space western to be well-verse'd in",
        "The winged tormentor from the pond Luke tried to sacrifice a nephew to",
        "Hamilton's smile",
        "A ball and a bar and a bear and a bee",
        "Angeline's catabasis",
        "Faith in the Blum Shopping Mall dollar store",
        "Jennings' absence and worldly light",
        "Fleeting passion in the Hand of Dithyramb",
        "The courage, my love, to dream bigger",
        "A crossover episode?",
        "My old scarf, nostalgia scented",
        "The fluffiest thirty minutes",
        "Alice | ecilA",
        "The sound found for Virtute",
        "Enough patience for a meaningful answer",
        "The bright and beautiful things astronauts see",
        "A puff of logic",
        "Coney Island Design & Construction",
        "Radwa or the lips of Radwa",
        "Alice, and her being alive despite it all",
        "A dead goose in a bush next to a lake",
        "Tapi's smile",
        "Perce's Rome",
        "Sensei Danya",
        "Sir Galahad's fatal favourite colour",
        "Bracegirdle's plumcakes",
        "A heart beyond human speech, sustained with jasmine, glass, birdcry and nothing more",
        "Morra's smile",
        "A conditional Vision",
        "Waketervenspiracies",
        "A sanctuary moon",
        "Noodles in the back",
        "The dragon either too much or too little",
        "Shreds of lettuce in the teeth",
        "Something true or nothing",
        "SodiumNeodymium",
        "Backpacks over purses (Odessan shrimp)",
        "Shifty rabbit, weird bird, greasy cat",
    ];
}
